### ISSUE TITLE
Warning when using Structure Field `style: table` and translated field labels

### ISSUE THREAD

**Issue by PaulMorel** [getkirby/toolkit#152]
As the title says, I get when I use the stucture field's `style: table` option and translated field labels in my blueprint.

Here's the error:

`Warning: htmlentities() expects parameter 1 to be string, array given in /var/www/html/kirby/toolkit/lib/html.php on line 109`

Here's the offending blueprint

```yml
    plans:
        label: Plans
        type: structure
        style: table
        fields:
            plan:
                label:
                    en: Title
                    fr: Titre
                type: text
            availability:
                label:
                    en: Availability
                    fr: Disponibilité
                type: number
                min: 0
                validate: num
            price:
                label:
                    en: Price
                    fr: Prix
                type: number
                min: 0
                validate: num
                icon: credit-card
                help:
                    en: Plan price before taxes
                    fr: Prix du plan avant taxes            
```

I'm assuming the labels are stored in an array when they're translated, `htmlentities()` expecting a string.

I think a check for the user's language is needed.
