### ISSUE TITLE
Bug: YAML trimmed too much

### ISSUE THREAD

**Issue by derhuerst** [getkirby/toolkit#28]
When parsing YAML, the Kirby toolkit trims the input too aggressively. This leads to wrong parsing in Kirby.

``` yaml
b:
    -
        c: >
            bla bla
            - bla
            - bla
        d: bla
    -
        c: >
            bla bla
            - bla
            - bla
        d: bla
```

The **correct** `var_dump` equivalent of the parsed `b` field:

```
array(2) {
    [0]=>
    array(2) {
        ["c"]=>
        string(19) "bla bla - bla - bla"
        ["d"]=>
        string(3) "bla"
    }
    [1]=>
    array(2) {
        ["c"]=>
        string(19) "bla bla - bla - bla"
        ["d"]=>
        string(3) "bla"
    }
}
```

The **actual** `var_dump` equivalent of the parsed `b` field:

```
array(1) {
    [0]=>
    array(3) {
        ["c"]=>
        string(19) "bla bla - bla - bla"
        ["d"]=>
        string(3) "bla"
        [0]=>
        array(2) {
            ["c"]=>
            string(19) "bla bla - bla - bla"
            ["d"]=>
            string(3) "bla"
        }
    }
}
```

I think, the `trim` command in [lib/yaml.php on line 44](https://github.com/getkirby/toolkit/blob/d2419bb10a404e96948524307d1a8ffe980f9051/lib/yaml.php#L44) has to be modified.
